In [1]:
from tensorflow.keras.preprocessing.text  import one_hot

In [2]:
## sentances
sent=[
'the glass of milk',
'the glass of juice',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good'
]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3547, 1904, 1027, 9550],
 [3547, 1904, 1027, 4771],
 [9815, 539, 4535, 1202, 5615],
 [9815, 539, 4535, 1202, 5156],
 [1262, 3547, 5045, 1027, 6006],
 [9927, 6005, 4930, 1202]]

In [5]:
## word embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [6]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3547 1904 1027 9550]
 [   0    0    0    0 3547 1904 1027 4771]
 [   0    0    0 9815  539 4535 1202 5615]
 [   0    0    0 9815  539 4535 1202 5156]
 [   0    0    0 1262 3547 5045 1027 6006]
 [   0    0    0    0 9927 6005 4930 1202]]


In [7]:
dim=10

In [8]:
## feature representation

model= Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\viv96\anaconda3\envs\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 556ms/step


array([[[-0.02330211,  0.01627814, -0.04349464,  0.02309198,
         -0.0032322 ,  0.01108183, -0.04514333, -0.00697652,
         -0.00330598, -0.02367705],
        [-0.02330211,  0.01627814, -0.04349464,  0.02309198,
         -0.0032322 ,  0.01108183, -0.04514333, -0.00697652,
         -0.00330598, -0.02367705],
        [-0.02330211,  0.01627814, -0.04349464,  0.02309198,
         -0.0032322 ,  0.01108183, -0.04514333, -0.00697652,
         -0.00330598, -0.02367705],
        [-0.02330211,  0.01627814, -0.04349464,  0.02309198,
         -0.0032322 ,  0.01108183, -0.04514333, -0.00697652,
         -0.00330598, -0.02367705],
        [ 0.02160083,  0.02624402,  0.0375005 , -0.04109714,
         -0.01176697, -0.02468352, -0.01452371,  0.00252197,
         -0.02251412,  0.04260239],
        [-0.04103637, -0.03638768,  0.00302026, -0.04552444,
          0.01547173, -0.01538966, -0.00760535, -0.00087966,
         -0.03987145, -0.03970847],
        [ 0.04432554, -0.02949274,  0.00618243,  0.0

In [11]:
embedded_docs[0]

array([   0,    0,    0,    0, 3547, 1904, 1027, 9550])